# Generated by Django 6.0.4 on 2026-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(default='vide', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Téléphone'),
        ),
    ]
