# Generated by Django 6.0.4 on 2026-04-14 20:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0002_alter_client_description_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit')),
                ('catégorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LE_CRM.catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
    ]
