# Generated by Django 6.0.4 on 2026-04-14 21:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0003_catégorie_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de la vente')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LE_CRM.client', verbose_name='Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LE_CRM.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
    ]
