# Generated by Django 6.0.4 on 2026-04-14 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0005_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('appel', 'Appel'), ('sms', 'SMS'), ('email', 'Email'), ('rendez_vous', 'Rendez-vous')], max_length=20, verbose_name="Type d'action")),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='a_faire', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LE_CRM.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-date_action'],
            },
        ),
    ]
