# Generated by Django 6.0.4 on 2026-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0006_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
    ]
