# Generated by Django 6.0.4 on 2026-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0007_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='stock_adjusted',
            field=models.BooleanField(default=False, verbose_name='Stock ajusté'),
        ),
    ]
