# Generated by Django 6.0.4 on 2026-04-22 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0008_vente_stock_adjusted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='source',
            field=models.CharField(choices=[('boutique', 'Boutique'), ('tiktok', 'TikTok'), ('autre', 'Autre')], default='boutique', max_length=50, verbose_name='Source de la vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
    ]
