# Generated by Django 6.0.4 on 2026-04-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LE_CRM', '0009_vente_source_vente_vendeur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
